In [2]:
import numpy as np
import pandas as pd

### `Hierarchical indexing`

In [3]:
data = pd.Series(np.random.randn(9), index=['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', ])

data.index

Index(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], dtype='object')

In [4]:
data1 = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3,  1, 3, 1, 2, 2, 3]]) # irarxik indeksli Ser
data1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
data1

a  1    0.916970
   2   -0.148991
   3   -1.091567
b  1    0.800895
   3   -0.232415
c  1    0.965474
   2   -1.407391
d  2    0.923532
   3   -0.436439
dtype: float64

In [6]:
data1['a']

1    0.916970
2   -0.148991
3   -1.091567
dtype: float64

In [7]:
data1["c":"d"]

c  1    0.965474
   2   -1.407391
d  2    0.923532
   3   -0.436439
dtype: float64

In [8]:
data1.loc[:, 2]

a   -0.148991
c   -1.407391
d    0.923532
dtype: float64

In [9]:
data1.loc[['a', 'b']]

a  1    0.916970
   2   -0.148991
   3   -1.091567
b  1    0.800895
   3   -0.232415
dtype: float64

### `unstack`

In [10]:
data1.unstack()

          1         2         3
a  0.916970 -0.148991 -1.091567
b  0.800895       NaN -0.232415
c  0.965474 -1.407391       NaN
d       NaN  0.923532 -0.436439

### **`stack`**

In [11]:
data1.unstack().stack()

a  1    0.916970
   2   -0.148991
   3   -1.091567
b  1    0.800895
   3   -0.232415
c  1    0.965474
   2   -1.407391
d  2    0.923532
   3   -0.436439
dtype: float64

In [12]:
!git clone https://github.com/MansurCompAI/Practicum_Datasets.git # Githubdagi reponi nusxalab oladi

Cloning into 'Practicum_Datasets'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 60 (delta 17), reused 16 (delta 1), pack-reused 0
Receiving objects: 100% (60/60), 20.24 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (17/17), done.

In [13]:
df = pd.read_csv("/content/Practicum_Datasets/world_cities_air_water_quality.csv")
df

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               3963 non-null   object
 1    "Region"          3963 non-null   object
 2    "Country"         3963 non-null   object
 3    "AirQuality"      3963 non-null   float64
 4    "WaterPollution"  3963 non-null   float64
dtypes: float64(2), object(3)
memory usage: 154.9+ KB

In [15]:
df.columns = df.columns.str.replace('"', "").str.strip()
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [16]:
# df['Region'] = df['Region'].map(lambda x:x.replace('"', ""))
df['Region'] = df['Region'].str.replace('"', " ")
df['Region']

0                     New York
1         District of Columbia
2                   California
3
4                   California
                 ...
3958           Medina Province
3959                 Andalusia
3960                 Catalonia
3961          Castile and Leon
3962          Castile and Leon
Name: Region, Length: 3963, dtype: object

In [17]:
df['Country'] = df['Country'].map(lambda x:x.replace('"', ""))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [18]:
df.to_csv("Updated_dataset.csv", index=False)

In [19]:
df[df['Country']=='Germany']

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [20]:
df['Country'][3]

' Germany'

In [21]:
df['Country'] = df['Country'].map(lambda x:x.strip())
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [22]:
df[df['Country']=='Germany']

,City,Region,Country,AirQuality,WaterPollution
3,Berlin,,Germany,62.364130,28.612717
28,Cologne,North Rhine-Westphalia,Germany,60.714286,27.777778
40,Bonn,North Rhine-Westphalia,Germany,82.812500,22.500000
52,Heilbronn,Baden-Wurttemberg,Germany,80.000000,0.000000
76,Aachen,North Rhine-Westphalia,Germany,70.454545,17.857143
...,...,...,...,...,...
2693,Bad Waldsee,Baden-Wurttemberg,Germany,100.000000,50.000000
2714,Weilheim in Oberbayern,Bavaria,Germany,100.000000,50.000000
2727,Buckow,Brandenburg,Germany,87.500000,50.000000
3942,Erfurt,Thuringia,Germany,85.000000,50.000000
3943,Garmisch-Partenkirchen,Bavaria,Germany,100.000000,50.000000

In [23]:
df[df['Country']=='Uzbekistan']

        City Region     Country  AirQuality  WaterPollution
21  Tashkent         Uzbekistan   56.451613       49.166667

In [24]:
df.to_csv("Updated_dataset.csv", index=False)

In [25]:
df.index

RangeIndex(start=0, stop=3963, step=1)

In [31]:
df.fillna(0, inplace=True)
df.replace({"  Faryab ": 0, "  Farah ":0, "  Herat ":0}, inplace=True)
df1=pd.pivot_table(df,index=["Country","City"])

TypeError: Could not convert   Kabul  to numeric

In [ ]:
df1.loc[['Uzbekistan', 'Germany', 'Tajikistan']]

In [ ]:
df2 = df1.copy()
df2

In [ ]:
df2['AirPollution'] = 100-df2['AirQuality']
df2

In [ ]:
df2['WaterQuality'] = 100-df2['WaterPollution']
df2

In [ ]:
df3 = pd.DataFrame(df2.values, index = df2.index, columns= [['AIR', 'AIR', 'WATER', 'WATER'], ['AirQuality', 'AirPollution', 'WaterQuality', 'WaterPollution']]) #
df3

In [ ]:
df3['AIR']

In [ ]:
df3

In [ ]:
df3.columns.names = ['Object', 'Info']
df3

In [ ]:
df3.index.names

In [ ]:
df3

### **` swaplevel `**

In [ ]:
df3.swaplevel('Country', 'City')

### **` sort_index `**

In [ ]:
df3.sort_index(level=0, ascending=False)

In [ ]:
3.1415926535